### PR TITLE
Fixed pipeline history range parsing errors

### LINKED ISSUE #1337: Parsing history index ranges fails
Running the `history` command with a single argument crashes with `FunctionClauseError`.

### PR DESCRIPTION
**Pull request by kevsmith**
Fixes #1337

### CODE REVIEW

File: lib/cog/repository/pipeline_history.ex [hunk 1]
```diff
@@ -77,6 +77,7 @@ defmodule Cog.Repository.PipelineHistory do
     query  = build_user_history_query(user_id, hist_start, hist_end, limit)
     query = from q in query,
             where: q.state == "finished"
+    IO.inspect query
```
Comment (vanstee) [inline lib/cog/repository/pipeline_history.ex]: Guessing this is left over debugging stuffs.

File: lib/cog/commands/history.ex [hunk 2]
```diff
@@ -35,25 +35,26 @@ defmodule Cog.Commands.History do
   end
 
   defp parse_args([]), do: {:ok, {nil, nil}}
-  defp parse_args([hist_start]) do
+  defp parse_args([hist_start]) when is_binary(hist_start) do
```
Comment (vanstee) [inline lib/cog/commands/history.ex]: Totally not a big deal, but it probably makes sense to call this parameter a `hist_range`

File: lib/cog/commands/history.ex [hunk 3]
```diff
@@ -65,6 +66,9 @@ defmodule Cog.Commands.History do
     with {:ok, hist_end} <- parse_int(hist_end),
       do: {:ok, {nil, hist_end}}
   end
```
Comment (vanstee) [inline lib/cog/commands/history.ex]: Are these function heads that include `"-"` still used? It doesn't look like the parser will parse `-` as a command arg and i couldn't figure out how else this was called.
