### PR TITLE
Overhaul executor error-handling

### LINKED ISSUE #416: Consolidate and improve pipeline error messaging
Currently, error messaging in the executor is all over the place. We should:

* Consolidate error handling in one place, rather than scattering it around the executor and related modules
* We should favor errors-as-data rather than errors-as-message-strings until we get to the very edge of the system. Pass error tuples around, with enough data as needed to generate actionable messages right before we send the response back to the user. This also facilitates a pattern-matching based approach to error handling (see, e.g., [here](https://github.com/operable/cog/blob/99b3b0d1a7bddda765f3dc7accbd803cdf277754/lib/cog/commands/permissions.ex#L229-L250))
* Provide context to the error (this is the important part of this issue). Once pipelines can be initiated outside of chat, we'll need a lot more information in errors in order for people to make sense of them. At a minimum we should provide:
  - the user that initiated the pipeline
  - timestamp when the pipeline was initiated
  - timestamp when the pipeline failed
  - the unique pipeline ID
  - the raw text of the pipeline as provided to the executor
  - the text of the bound command invocation that failed
  - the error message

Incidentally, this context will be helpful for human-initiated pipelines as well (think busy channels, and long-running pipelines)

### PR DESCRIPTION
**Pull request by christophermaier**
Previously, error messages were generated in a number of places, making
it difficult to get a grasp on the variety of responses generated.

Additionally, error messages did not contain all that much context about
the error, something we'd need to address before allowing pipelines to
be triggered by external events.

Here, (almost) all error handling is consolidated into one place in the executor,
with lots of additional context added.

(Error messages for people lacking a Cog account, as well as for bad
redirects, are still handled as they were, since these were already
complex messages. Once we have error templates, everything will be able
to be consolidated even further.)

Tests have been updated, but in an admittedly less-than-satisfying
way. They are still strongly coupled to the exact output of the error
messages, but upcoming work to template error responses will,
interestingly enough, allow us to perform comparisons on data
structures, and not text, which will make the tests more robust in the
face of future changes.

Fixes #416

### CODE REVIEW

File: lib/cog/command/pipeline/executor.ex [hunk 1]
```diff
@@ -284,6 +266,8 @@ defmodule Cog.Command.Pipeline.Executor do
                                    # one flat list
                                end
             {:next_state, :execute_plan, %{state | output: collected_output}, 0}
+          "error" ->
+            fail_pipeline_with_error({:command_error, resp}, state)
```
Comment (vanstee) [inline lib/cog/command/pipeline/executor.ex]: :+1: I like having `error` cases below `ok` ones when possible.

File: lib/cog/command/pipeline/executor.ex [hunk 2]
```diff
@@ -677,35 +663,160 @@ defmodule Cog.Command.Pipeline.Executor do
...
-  end
+  # Create a standard error message for pipeline-related
+  # errors. Eventually this will be templated.
+  defp user_error(error, state) do
+    id = state.id
+    started = Cog.Events.Util.ts_iso8601_utc(state.started)
+    initiator = sender_mention_name(state)
+    pipeline_text = state.request["text"]
+    error_message = format_user_error(error, state)
+    failing = case state.current_plan do
```
Comment (vanstee) [inline lib/cog/command/pipeline/executor.ex]: Instead of doing this dance to figure out what failed during execution, would it be worth storing `failing` in `state`? Not sure if that's a great idea or not, but it does seem like it would clean up a bit of this logic.

File: lib/cog/command/pipeline/executor.ex [hunk 3]
```diff
@@ -677,35 +663,160 @@ defmodule Cog.Command.Pipeline.Executor do
...
+
+    # If the failure happened during planning or execution, we'll have
+    # a bit more information to show
+    command_text = case failing do
+                     %Ast.Invocation{} ->
+                     """
+                     The pipeline failed planning the invocation:
+
+                         `#{failing}`
+                     """
```
Comment (vanstee) [inline lib/cog/command/pipeline/executor.ex]: I don't really have an opinion about including a line at the end or not, but we should be consistent about it. See line 718. Also fwiw the end of a heredoc includes a new line.

File: lib/cog/command/pipeline/executor.ex [hunk 4]
```diff
@@ -677,35 +663,160 @@ defmodule Cog.Command.Pipeline.Executor do
...
+  defp format_user_error({:disabled_bundle, %Cog.Models.Bundle{name: name}}, _state),
+    do: "Whoops! An error occurred. The #{name} bundle is currently disabled"
+  defp format_user_error({:timeout, %Cog.Models.Command{}=command}, _state) do
+    name = Cog.Models.Command.full_name(command)
+    "The #{name} command timed out"
+  end
+  defp format_user_error({:template_rendering_error, {error, template, adapter}}, _state),
+    do: "Whoops! An error occurred. There was an error rendering the template '#{template}' for the adapter '#{adapter}': #{inspect error}"
+  defp format_user_error({:command_error, response}, _state),
+    do: "Whoops! An error occurred. " <> (response.status_message || response.body["message"])
```
Comment (vanstee) [inline lib/cog/command/pipeline/executor.ex]: :+1: Having all these error messages together will help us keep the wording consistent as well.

**Comment by vanstee** [comment]
Looks good. We really needed this refactor.

File: lib/cog/command/pipeline/executor.ex (hunk 2 above)
Comment (christophermaier) [inline lib/cog/command/pipeline/executor.ex]: Possibly, yeah. I think this will probably shake out in the implementation of #470. 

Sound OK to leave it until then?

File: lib/cog/command/pipeline/executor.ex (hunk 3 above)
Comment (christophermaier) [inline lib/cog/command/pipeline/executor.ex]: D'oh!

Think this could wait until #470 as well?

File: lib/cog/command/pipeline/executor.ex (hunk 4 above)
Comment (christophermaier) [inline lib/cog/command/pipeline/executor.ex]: Yup. I'd love to take another pass through these and unify the wording.
