### PR TITLE
Fix history command bugs

### LINKED ISSUE #1364: `history -l 1` crashes
We need to make sure we can return a single value from history. Also we should check the limit to make sure it isn't a negative number.

screen shot 2017-02-21 at 11 26 15 am

### PR DESCRIPTION
**Pull request by vanstee**
* Limit 1 returns the expected result
* Negative limits cause an abort with error message

Fixes #1364

### CODE REVIEW

File: lib/cog/commands/history.ex [hunk 1]
```diff
@@ -83,8 +83,16 @@ defmodule Cog.Commands.History do
     end
   end
 
+  defp ensure_positive_limit(limit) do
```
Comment (kevsmith) [inline lib/cog/commands/history.ex]: I think it's more concise to use multiple function heads here

```
defp ensure_positive_limit(n) when n < 0, 
  do: {:error, "Limit must be a positive integer"}
defp ensure_positive_limit(n) when n >= 0, do: {:ok, n}
```

Comment (vanstee) [inline lib/cog/commands/history.ex]: Ah good call.
