### PR TITLE
Replace escaped double quotes with double quotes

### LINKED ISSUE #1323: Parsing escaped quotes in json fails
`@cog seed "[{\"test\": \"test\"}]"` fails, when it should succeed.

### PR DESCRIPTION
**Pull request by kevsmith**
Fixes `Cog.Command.Seed` crash triggered when given a string containing escaped double quotes.

Fixes #1323

### CODE REVIEW

File: lib/cog/commands/seed.ex [hunk 1]
```diff
@@ -30,6 +30,7 @@ defmodule Cog.Command.Seed do
   def handle_message(%Command{args: [input]}=req, state) when not(is_binary(input)),
     do: {:error, req.reply_to, "Argument must be a string", state}
   def handle_message(%Command{args: [input]}=req, state) do
+    input = String.replace(input, ~r/\\\"/, "\"")
```
Comment (vanstee) [inline lib/cog/commands/seed.ex]: Do we also need to do this for single quotes?
